# Generated by Django 4.0.5 on 2022-08-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic__views_alter_topic_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='_views',
            new_name='views',
        ),
    ]
